name: Build Any Wheel

on:
  push:
    branches:
      - main
      - 'releases/**'

permissions: {}

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: '3.12'

      - name: build wheel
        run: python -m pip wheel . -v

      - name: install twine
        run: python -m pip install twine

      - name: check wheel
        run: python -m twine check ./onnxmltools*.whl

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          path: ./skl2onnx*.whl
